results = [
    {
      "title": "البند 2",
      "description": "يُحظر على مقدم الخدمة مشاركة البيانات دون موافقة المستخدم.",
      "source": "تنظيمات الحد من الرسائل والمكالمات الاقتحامية_response.docx",
      "page": "Page not specified",
      "clause_instruction": {
        "description_control": "يُحظر على مقدم الخدمة مشاركة البيانات دون موافقة المستخدم، أي أن مقدم الخدمة لا يُسمح له بمشاركة أي بيانات شخصية للمستخدمين إلا إذا تمت الموافقة على ذلك من المستخدم. كما يُعتبر أي تصرف يُخالف هذه规定 غير مقبول ومخالف للوائح.",
        "requirements_control": {
          "Audit_Instructions": [
            "Step 1: اقرأ جميع الأقسام والتفاصيل المتعلقة بمشاركة البيانات في المستند.",
            "Step 2: تحقق من أن أي إشارة إلى مشاركة البيانات تُصاحبتها موافقة من المستخدم.",
            "Step 3: حدد جميع الحالات التي تُشير إلى مشاركة البيانات دون موافقة المستخدم.",
            "Step 4: علّق أي إشارة أو تفصيل يُشير إلى مشاركة البيانات دون موافقة المستخدم كمخالفة."
          ]
        }
      },
      "clause_audit_instruction": "You are a legal and regulatory compliance expert.\n\nYour task is to review the provided image (e.g., a screenshot, scanned policy, or official document) and determine whether it demonstrates compliance with the following clause requirement.\n\nThe clause is defined using structured, measurable elements, and includes the responsible party, required action, applicable conditions, and a detailed list of audit instructions.\n\n---\n### 📜 Clause Instruction:\n{\n  \"description_control\": \"يُحظر على مقدم الخدمة مشاركة البيانات دون موافقة المستخدم، أي أن مقدم الخدمة لا يُسمح له بمشاركة أي بيانات شخصية للمستخدمين إلا إذا تمت الموافقة على ذلك من المستخدم. كما يُعتبر أي تصرف يُخالف هذه规定 غير مقبول ومخالف للوائح.\",\n  \"requirements_control\": {\n    \"Audit_Instructions\": [\n      \"Step 1: اقرأ جميع الأقسام والتفاصيل المتعلقة بمشاركة البيانات في المستند.\",\n      \"Step 2: تحقق من أن أي إشارة إلى مشاركة البيانات تُصاحبتها موافقة من المستخدم.\",\n      \"Step 3: حدد جميع الحالات التي تُشير إلى مشاركة البيانات دون موافقة المستخدم.\",\n      \"Step 4: علّق أي إشارة أو تفصيل يُشير إلى مشاركة البيانات دون موافقة المستخدم كمخالفة.\"\n    ]\n  }\n}\n---\n\n### 🔍 Your Evaluation Task:\n\nYou must analyze the image and confirm whether it fulfills the clause requirements as follows:\n\n1. **Responsible Party**  \n   Verify that the party mentioned in the image matches the responsible entity stated in the clause.\n\n2. **Required Action**  \n   Ensure that the expected action (e.g., prohibition, obligation, or condition) is clearly addressed or implemented in the evidence.\n\n3. **Condition (if applicable)**  \n   If any conditions are specified, check that they are satisfied explicitly within the content of the image.\n\n4. **Audit Instructions**  \n   Follow the list of audit steps included in the clause. These steps define exactly what to look for to determine compliance.\n\n---\n\n### ✅ Final Compliance Decision:\n\nPlease provide your conclusion using one of the following decisions:\n\n- **COMPLIANT**: The image clearly demonstrates full adherence to the clause requirements and satisfies all audit instructions.\n- **NON-COMPLIANT**: One or more clause elements are not satisfied, unclear, or missing in the image.\n- **INDECISIVE**: The image lacks enough detail to assess compliance with confidence.\n\nIf NON-COMPLIANT or INDECISIVE, explain briefly which parts are missing or unsupported and what evidence would be needed to confirm compliance."
    },
    {
      "title": "البند 5",
      "description": "الشروط واألحكام العامة والخاصة لتقديم خدمة الرسائل القصيرة (SMS)",
      "source": "تنظيمات تقديم خدمات الرسائل القصيرة_response.docx",
      "page": "Page not specified",
      "clause_instruction": {
        "description_control": "يجب على مقدم الخدمة أن يلتزم بتطبيق الشروط والأحكام العامة والخاصة لتقديم خدمة الرسائل القصيرة (SMS) بشكل كامل ودقيق، بما في ذلك الالتزام بجميع القواعد والإجراءات المتعلقة بتقديم خدمات SMS، وضمان أن يتم تنفيذ هذه الشروط والأحكام بشكل منتظم ومتبعًا لجميع الظروف والمتطلبات المحددة في النظام واللوائح ذات الصلة.",
        "requirements_control": {
          "Audit_Instructions": [
            "Step 1: تحقق من وجود شروط وأحكام مفصلة وواضحة تتعلق بتقديم خدمة الرسائل القصيرة (SMS) في المستند.",
            "Step 2: تأكد من أن الشروط والأحكام تشمل جميع الجوانب المتعلقة بتقديم خدمة SMS، مثل شروط الاستخدام، وسياسات الخصوصية، وشروط الدفع، وسياسات الإلغاء.",
            "Step 3: تحقق من أن الشروط والأحكام تُحدد بشكل واضح متطلبات وإجراءات مقدم الخدمة لتقديم خدمة SMS، بما في ذلك التزامات المُستخدمين.",
            "Step 4: تأكد من أن الشروط والأحكام تُنطبق على جميع الحالات والظروف التي تتعلق بخدمة SMS، بما في ذلك حالات الاستخدام غير المخطط له أو التغييرات في خدمات SMS."
          ]
        }
      },
      "clause_audit_instruction": "You are a legal and regulatory compliance expert.\n\nYour task is to review the provided image (e.g., a screenshot, scanned policy, or official document) and determine whether it demonstrates compliance with the following clause requirement.\n\nThe clause is defined using structured, measurable elements, and includes the responsible party, required action, applicable conditions, and a detailed list of audit instructions.\n\n---\n### 📜 Clause Instruction:\n{\n  \"description_control\": \"يجب على مقدم الخدمة أن يلتزم بتطبيق الشروط والأحكام العامة والخاصة لتقديم خدمة الرسائل القصيرة (SMS) بشكل كامل ودقيق، بما في ذلك الالتزام بجميع القواعد والإجراءات المتعلقة بتقديم خدمات SMS، وضمان أن يتم تنفيذ هذه الشروط والأحكام بشكل منتظم ومتبعًا لجميع الظروف والمتطلبات المحددة في النظام واللوائح ذات الصلة.\",\n  \"requirements_control\": {\n    \"Audit_Instructions\": [\n      \"Step 1: تحقق من وجود شروط وأحكام مفصلة وواضحة تتعلق بتقديم خدمة الرسائل القصيرة (SMS) في المستند.\",\n      \"Step 2: تأكد من أن الشروط والأحكام تشمل جميع الجوانب المتعلقة بتقديم خدمة SMS، مثل شروط الاستخدام، وسياسات الخصوصية، وشروط الدفع، وسياسات الإلغاء.\",\n      \"Step 3: تحقق من أن الشروط والأحكام تُحدد بشكل واضح متطلبات وإجراءات مقدم الخدمة لتقديم خدمة SMS، بما في ذلك التزامات المُستخدمين.\",\n      \"Step 4: تأكد من أن الشروط والأحكام تُنطبق على جميع الحالات والظروف التي تتعلق بخدمة SMS، بما في ذلك حالات الاستخدام غير المخطط له أو التغييرات في خدمات SMS.\"\n    ]\n  }\n}\n---\n\n### 🔍 Your Evaluation Task:\n\nYou must analyze the image and confirm whether it fulfills the clause requirements as follows:\n\n1. **Responsible Party**  \n   Verify that the party mentioned in the image matches the responsible entity stated in the clause.\n\n2. **Required Action**  \n   Ensure that the expected action (e.g., prohibition, obligation, or condition) is clearly addressed or implemented in the evidence.\n\n3. **Condition (if applicable)**  \n   If any conditions are specified, check that they are satisfied explicitly within the content of the image.\n\n4. **Audit Instructions**  \n   Follow the list of audit steps included in the clause. These steps define exactly what to look for to determine compliance.\n\n---\n\n### ✅ Final Compliance Decision:\n\nPlease provide your conclusion using one of the following decisions:\n\n- **COMPLIANT**: The image clearly demonstrates full adherence to the clause requirements and satisfies all audit instructions.\n- **NON-COMPLIANT**: One or more clause elements are not satisfied, unclear, or missing in the image.\n- **INDECISIVE**: The image lacks enough detail to assess compliance with confidence.\n\nIf NON-COMPLIANT or INDECISIVE, explain briefly which parts are missing or unsupported and what evidence would be needed to confirm compliance."
    },
]

for r in results:
    print(r['title'])
    print(r['clause_instruction']['description_control'])
    print(r['clause_instruction']['requirements_control']['Audit_Instructions'])